/**
 * Loads the song library from the pre-built index in public/choro-index.json.
 *
 * The index is a compact array of [author, title, pdfPaths] tuples generated by
 * `npm run build:index`. Expanding it here keeps the payload small while handing
 * the rest of the app the shape it already expects.
 */

const INDEX_URL = `${process.env.BASE_URL || '/'}choro-index.json`
const RAW_BASE = 'https://raw.githubusercontent.com/gazaboo/choro-db/main/'

/**
 * Splits a choro-db filename into its fields. They are laid out as
 *   "Author - Title - Type - Instrument[ - variant N]"
 * and the instrument sometimes carries a "(1)" disambiguating suffix.
 *
 * Reading the fields positionally rather than searching the whole string matters:
 * 72 files write the instrument as plain "Bb"/"Eb" instead of "Clarinet Bb"/
 * "Saxophone Eb", and a substring search silently filed all of them under C —
 * where they then overwrote the song's real C score.
 */
function parseFilename(filename) {
  const parts = filename.split(' - ')
  const type = (parts[2] || '').trim()
  const instrument = (parts[3] || '').replace(/\(\d+\)\s*$/, '').trim()

  let key = 'C'
  if (/^(Clarinet\s+)?Bb$/i.test(instrument)) key = 'Bb'
  else if (/^(Saxophone\s+)?Eb$/i.test(instrument)) key = 'Eb'

  // The repository uses both spellings; 12 files say "Contracanto".
  return { key, isContracanto: /^contra(ponto|canto)$/i.test(type) }
}

function expandSong([author, title, paths]) {
  const song = { title, author, melody: {}, contracanto: {}, pdfs: [] }

  for (const path of paths) {
    const filename = path.split('/').pop().slice(0, -'.pdf'.length)
    const { key, isContracanto } = parseFilename(filename)
    const url = RAW_BASE + encodeURIComponent(path)

    // One entry per instrument key; later variants of the same key win, and the
    // full set stays available through `pdfs`.
    if (isContracanto) song.contracanto[key] = url
    else song.melody[key] = url

    song.pdfs.push({
      url,
      filename,
      key,
      type: isContracanto ? 'Contracanto' : 'Theme'
    })
  }

  return song
}

export async function loadChoroLibrary() {
  const response = await fetch(INDEX_URL)
  if (!response.ok) {
    throw new Error(`Could not load the song index (HTTP ${response.status})`)
  }
  const index = await response.json()
  return index.map(expandSong)
}
