/**
 * Loads the song library from the pre-built index in public/choro-index.json.
 *
 * The index is a compact array of [author, title, pdfPaths] tuples generated by
 * `npm run build:index`. Expanding it here keeps the payload small (~330 KiB raw,
 * ~34 KiB gzipped) while handing the rest of the app the shape it already expects.
 */

const INDEX_URL = `${process.env.BASE_URL || '/'}choro-index.json`
const RAW_BASE = 'https://raw.githubusercontent.com/gazaboo/choro-db/main/'

/** Derives the instrument key a PDF is written for from its filename. */
function instrumentKeyOf(filename) {
  if (filename.includes('Clarinet Bb')) return 'Bb'
  if (filename.includes('Saxophone Eb')) return 'Eb'
  return 'C'
}

function expandSong([author, title, paths]) {
  const song = { title, author, melody: {}, contracanto: {}, pdfs: [] }

  for (const path of paths) {
    const filename = path.split('/').pop().slice(0, -'.pdf'.length)
    const key = instrumentKeyOf(filename)
    const isContracanto = filename.toLowerCase().includes('contraponto')
    const url = RAW_BASE + encodeURIComponent(path)

    // One entry per instrument key; later variants of the same key win, and the
    // full set stays available through `pdfs`.
    if (isContracanto) song.contracanto[key] = url
    else song.melody[key] = url

    song.pdfs.push({
      url,
      filename,
      key,
      type: isContracanto ? 'Contracanto' : 'Theme'
    })
  }

  return song
}

export async function loadChoroLibrary() {
  const response = await fetch(INDEX_URL)
  if (!response.ok) {
    throw new Error(`Could not load the song index (HTTP ${response.status})`)
  }
  const index = await response.json()
  return index.map(expandSong)
}
